setup:
  timeout: 1200
  memout: 1024
source:
  path: .
  format: one-file
data:
  default-values:
    status: UNKNOWN
    nSolutions: 0
    cores: 1
    threads: 1
    failures: 0
    propagations: 0
    datetime: null
    method: satisfy
  raw-data:
    - log-data: status
      file: "*.log"
      pattern: "s {word}"
    - log-data: objective
      file: "*.log"
      pattern: "BOUND {integer}"
    - log-data: solutions
      file: "*.log"
      pattern: "FOUND SOLUTIONS {integer}"
    - log-data: cpu_time 
      file: "*.log"
      pattern: "c real time : {real}"
    - log-data: method
      file: "*.log"
      pattern: "way:{word}"
    - log-data: cores
      file: "*.log"
      pattern: "cores: {integer}"
    - log-data: threads
      file: "*.log"
      pattern: "threads: {integer}"
    - log-data: datetime
      file: "*.log"
      pattern: "datetime: {any}"
    - log-data: experiment_ware
      file: "*.log"
      pattern: "experiment_ware: {any}"
    - log-data: options
      file: "*.log"
      pattern: "extras: {any}"